# Generated by Django 3.1 on 2020-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200906_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avalible_seats',
        ),
        migrations.AddField(
            model_name='course',
            name='avalibility',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
